import Graph from "https://esm.sh/graphology@0.26.0";
import {parse} from "https://esm.sh/graphology-gexf@0.13.2/browser";
import Sigma from "https://esm.sh/sigma@3.0.2";
const $=s=>document.querySelector(s),loader=$("#loader"),loaderMessage=$("#loader-message"),progressBar=$("#progress-bar"),searchInput=$("#movie-search"),suggestions=$("#suggestions"),selection=$("#selection");
let graph,renderer,selectedNode=null,hoveredNode=null,neighborhood=null;
const hash=value=>{let h=2166136261;for(let i=0;i<value.length;i++)h=Math.imul(h^value.charCodeAt(i),16777619);return(h>>>0)/4294967295};
function prepareGraph(){let maxDegree=1;graph.forEachNode(n=>maxDegree=Math.max(maxDegree,graph.degree(n)));graph.forEachNode((n,a)=>{const d=graph.degree(n),angle=hash(n)*Math.PI*2,r=Math.sqrt(hash(`${n}:radius`));graph.mergeNodeAttributes(n,{label:a.label||n,x:Math.cos(angle)*r,y:Math.sin(angle)*r,size:1.4+5.5*Math.sqrt(d/maxDegree),color:d>maxDegree*.12?"#dd6b3f":"#567764",degree:d})});graph.forEachEdge((e,a)=>{const w=Number(a.weight)||1;graph.mergeEdgeAttributes(e,{weight:w,size:Math.min(2,.15+Math.log1p(w)*.18),color:"rgba(88,116,97,0.16)"})})}
function setReducers(){renderer.setSetting("nodeReducer",(n,d)=>{const r={...d};if(selectedNode||hoveredNode){const focus=selectedNode||hoveredNode,visible=n===focus||neighborhood?.has(n);if(!visible){r.color="#d6ddd4";r.label="";r.zIndex=0}else{r.zIndex=2;r.forceLabel=true}}if(n===selectedNode||n===hoveredNode){r.color="#dd6b3f";r.size=Math.max(d.size*1.8,9);r.zIndex=3}return r});renderer.setSetting("edgeReducer",(e,d)=>{if(!selectedNode&&!hoveredNode)return d;const focus=selectedNode||hoveredNode,[s,t]=graph.extremities(e);return s===focus||t===focus?{...d,color:"rgba(221,107,63,.72)",size:Math.max(d.size,1.2),zIndex:2}:{...d,hidden:true}})}
function setFocus(node,move=true){selectedNode=node;neighborhood=new Set(graph.neighbors(node));neighborhood.add(node);const a=graph.getNodeAttributes(node);let weight=0;graph.forEachEdge(node,(_e,x)=>weight+=Number(x.weight)||1);$("#selected-title").textContent=a.label;$("#selected-links").textContent=graph.degree(node).toLocaleString();$("#selected-strength").textContent=weight.toLocaleString();selection.hidden=false;searchInput.value=a.label;$("#clear-search").hidden=false;suggestions.hidden=true;if(move)renderer.getCamera().animate({x:a.x,y:a.y,ratio:.08},{duration:650});renderer.refresh()}
function clearFocus(){selectedNode=hoveredNode=null;neighborhood=null;selection.hidden=true;searchInput.value="";$("#clear-search").hidden=true;suggestions.hidden=true;renderer.getCamera().animatedReset({duration:550});renderer.refresh()}
function showSuggestions(query){const q=query.trim().toLowerCase();suggestions.replaceChildren();if(!q){suggestions.hidden=true;return}const matches=[];graph.forEachNode((n,a)=>{const label=a.label||n,lower=label.toLowerCase();if(lower.includes(q))matches.push({node:n,label,starts:lower.startsWith(q),degree:a.degree})});matches.sort((a,b)=>Number(b.starts)-Number(a.starts)||b.degree-a.degree||a.label.localeCompare(b.label));for(const m of matches.slice(0,7)){const b=document.createElement("button");b.type="button";b.role="option";b.textContent=m.label;b.addEventListener("click",()=>setFocus(m.node));suggestions.append(b)}suggestions.hidden=!matches.length}
async function loadGraph(){try{const response=await fetch("network/movie_net.gexf");if(!response.ok)throw new Error(`Graph download failed (${response.status})`);const total=Number(response.headers.get("content-length"))||0,reader=response.body.getReader(),chunks=[];let received=0;while(true){const{done,value}=await reader.read();if(done)break;chunks.push(value);received+=value.length;if(total)progressBar.style.width=`${Math.min(65,received/total*65)}%`;loaderMessage.textContent=total?`Downloading graph data… ${Math.round(received/total*100)}%`:`Downloading graph data… ${(received/1048576).toFixed(1)} MB`}loaderMessage.textContent="Parsing 428,511 connections…";progressBar.style.width="72%";graph=parse(Graph,await new Blob(chunks).text(),{addMissingNodes:true});loaderMessage.textContent="Preparing the visualization…";progressBar.style.width="86%";await new Promise(r=>requestAnimationFrame(r));prepareGraph();renderer=new Sigma(graph,$("#graph"),{defaultNodeColor:"#567764",defaultEdgeColor:"rgba(88,116,97,0.16)",labelFont:"DM Sans, sans-serif",labelColor:{color:"#17211b"},labelDensity:.06,labelGridCellSize:120,labelRenderedSizeThreshold:5,renderEdgeLabels:false,hideEdgesOnMove:true,zIndex:true});setReducers();renderer.on("enterNode",({node})=>{if(selectedNode)return;hoveredNode=node;neighborhood=new Set(graph.neighbors(node));neighborhood.add(node);renderer.getContainer().style.cursor="pointer";renderer.refresh()});renderer.on("leaveNode",()=>{if(selectedNode)return;hoveredNode=null;neighborhood=null;renderer.getContainer().style.cursor="grab";renderer.refresh()});renderer.on("clickNode",({node})=>setFocus(node,false));renderer.on("clickStage",clearFocus);$("#node-count").textContent=graph.order.toLocaleString();$("#edge-count").textContent=graph.size.toLocaleString();searchInput.disabled=false;progressBar.style.width="100%";loaderMessage.textContent="Ready";setTimeout(()=>loader.classList.add("done"),250)}catch(error){console.error(error);loader.querySelector("strong").textContent="Could not load the network";loaderMessage.textContent="Serve this folder over HTTP and check that network/movie_net.gexf is present.";progressBar.style.background="#dd6b3f"}}
searchInput.addEventListener("input",e=>{$("#clear-search").hidden=!e.target.value;showSuggestions(e.target.value)});$("#search-form").addEventListener("submit",e=>{e.preventDefault();suggestions.querySelector("button")?.click()});$("#clear-search").addEventListener("click",clearFocus);$("#reset-selection").addEventListener("click",clearFocus);$("#zoom-in").addEventListener("click",()=>renderer.getCamera().animatedZoom({duration:250}));$("#zoom-out").addEventListener("click",()=>renderer.getCamera().animatedUnzoom({duration:250}));$("#reset-camera").addEventListener("click",clearFocus);document.addEventListener("click",e=>{if(!e.target.closest(".search"))suggestions.hidden=true});loadGraph();
